export { Strategy } from "./Strategy"
export { Hero } from "./Hero"
export { Presales } from "./Presales"
export { Tokonomics } from "./Tokonomics"
export {FAQs} from "./FAQs_"
export { Footer } from "./Footer"
